fun main() {
    val phone = MobilePhone(generatePhoneNumber())
    println("Контакты до добавления:")
    phone.printContacts()
    phone.addNewContact(Contact("8 800 535 35-35","Bill"))
    println("Контакты после добавления:")
    phone.printContacts()
    val bill = phone.queryContact("Bill")
    println("Контакт, найденный по имени:")
    println(bill)
    println("Полученный индекс контакта: " + phone.findContact(bill!!))
    println("Обновление контакта: " + phone.updateContact(bill, Contact("8 900 646 46-46", "Boll")))
    println("Контакты после обновления:")
    phone.printContacts()

    val tree = BinaryTree()
    tree.insert(4)
    tree.insert(2)
    tree.insert(3)
    tree.insert(6)
    tree.insert(5)
    tree.insert(8)
    tree.insert(7)
    tree.insert(9)
    println("Дерево до удаления: " + tree.traverse())
    println("Поиск ветви: " + tree.find(5))
    tree.remove(5)
    println("Дерево после удаления: " + tree.traverse())
}